### ISSUE TITLE
1.9.4-9.1.1 crashes dedicated forge server 1.9.4 build 1921 on startup

### ISSUE THREAD

**Issue by kreezxil** [TheTemportalist/Origin#1]
Issue: origin-1.9.4-9.1.1 crashes dedicated forge server 1.9.4 build 1921 on startup

crash report:
https://gist.github.com/6b8caae4cd612c1f62071c211e49775a

fml server latest:
https://gist.github.com/60ba2edb9d3d134a2cf68f4951e1192b

**Comment by TheTemportalist** [comment]
It's your Forge Version. Forge must have update the enum helper. Either use an earlier forge version, or wait till I can patch later.

**Comment by TheTemportalist** [comment]
Also, you should be made aware that this is NOT an Origin issue. This is an issue with Compression. This issue will be closed tomorrow (so that I don't forget about it), but it will not be solved in the context of this issue tracker and repository. It will be fixed soon in the Compression repository at TheTemportalist/Compression. It is your perogative should you decide to create a new issue in the appropriate issue tracker.

**Comment by TheTemportalist** [comment]
https://github.com/TheTemportalist/Compression/commit/3b4a3ac574e7ba8ac61a5cc827aac864dc7507ed
